### PR TITLE
Add __all__ dictionary, for pyright completion

### PR DESCRIPTION
**Pull request by nagua**
Hello @ronf,

as discussed in #485 I created added a `__all__` symbol to the `__init__.py` file.

What do you think of this?

Have a nice day!

### CODE REVIEW

**Comment by ronf** [comment]
Thanks for this. I'm probably going to want to trim this a little so that it only lists symbols which are meant to be public. In particular, the packages at the end (lines 265-272) should not be considered public, even though I had to import them to trigger register function calls in them. I'll also probably want to reorder the list to be alphabetical to make it easier to see whether a symbol is present or not, and also put more than one entry per line so more of the symbols can be visible at once.

That said, the important question is whether this was sufficient to get pyright to work the way you wanted here. Was it?

**Comment by nagua** [comment]
Yes, `pyright` can now successfully give autocompletions for `asyncssh`. I can sort the list if you want. I didn't want to have all modules in one line and I couldn't find any formatting guidelines, so I just used `black` for formatting and that was what it came up with. So feel free to suggest a different formatting scheme.

For the private modules: Should I just delete lines 265-272?

**Comment by ronf** [comment]
> For the private modules: Should I just delete lines 265-272?

Yes - I think that'd probably be best.

There are a handful other symbols in the list which are currently undocumented and not really meant for client use, but some of them show up in type annotations, so perhaps they should be included. I'm thinking of things like SSHForwarder and various  "Factory" types.

Regarding the formatting, I generally try to line wrap somewhere around 75 characters, occasionally letting it go to 79
if needed to break on a word boundary. Anything wider should wrap a word earlier, even if that makes the line  less than 75 characters wide, but fitting as much as it can on each line within those limits. I'm good with the `__all__ = [` and the trailing `]` on lines by themselves, and everything in between being indented 4 spaces. It'd just be good to sort the symbols and then combine them onto fewer lines.

Also, it looks like a space got added on line 76. It might be good to remove that to reduce noise.

**Comment by llchan** [comment]
Might I suggest that we sort the `__all__` list so that it's simpler to merge/insert lines?

**Comment by ronf** [comment]
Yes, that's the plan.

**Comment by ronf** [comment]
Thanks, @nagua !

I was able to confirm here that this change does silence the pyright warnings, and the formatting generally looks good. Just one final request before I merge it: Could you change all the double quotes to single quotes? The AsyncSSH default style is to use single quotes for all string constants, unless a string contains single quotes in its value.

**Comment by nagua** [comment]
Ok, the quotes are single quotes now.

**Comment by ronf** [comment]
Thanks so much, @nagua -- this is now merged into the "develop" branch and will be included in the next release!

**Pull request merged**
