### PR TITLE
explicitly pass provided loop to child objects

### PR DESCRIPTION
**Pull request by rutsky**
Good way to test is loop is properly passed is to set
global loop to None at the start of a program:

```
loop = asyncio.get_event_loop()
asyncio.set_event_loop(None)
```

### CODE REVIEW

**Comment by ronf** [comment]
Thanks for catching and submitting this! I'm traveling at the moment, but I'll merge this into the "develop" branch as soon as I'm back and get the fix into the next release.

**Comment by ronf** [comment]
I have merged these changes into the "develop" branch, along with some additional fixes of the same sort in the listener, SFTP, and X11 code. I'll get them in the master branch and into a new release soon. Thanks again for your contribution!

**Comment by rutsky** [comment]
@ronf thanks! When do you plan to do next release?

**Comment by ronf** [comment]
This should be part of 1.8.0, which I'm hoping to get out some time this week.

**Comment by ronf** [comment]
These fixes are now released in AsyncSSH 1.8.0.

**Comment by rutsky** [comment]
@ronf thanks!

**Pull request closed without merging**
