### PR TITLE
forward passphrase to agent.get_keys()

### PR DESCRIPTION
**Pull request by obeleh**
This fixes an issue for me where I tried to supply the passphrase but it wasn't used

### CODE REVIEW

**Comment by ronf** [comment]
I don't understand - the get_keys() method does not accept a passphrase argument, and doesn't need one. The private keys are kept in the agent and the passphrase (if needed) would have been provided when the keys were loaded by the agent. It is not needed when the SSHClientConnection queries the agent for the list of available keys.

**Comment by obeleh** [comment]
You're right. I copied the change wrong. Let me fix it

**Comment by obeleh** [comment]
Just ignore the PR. I see it was fixed already. Sorry for bothering you

**Comment by ronf** [comment]
No worries. Was this the issue in the non-agent case where the passphrase wasn't being used when reading the default client keys (69f1524)?

**Comment by obeleh** [comment]
yes

**Pull request closed without merging**
